name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.0
authors:
  - Hurshi <ihsruh@gmail.com>
  - Eric Kok <erickok@gmail.com>
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  quiver: ^3.2.1
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
